---
kind: pipeline
name: default
type: docker

trigger:
  branch:
    exclude:
      - gh-pages
      - github-pages

steps:
  - name: test
    image: rust:1.30
    commands:
      - rustup self update && rustup toolchain uninstall stable && rustup toolchain install stable
      - cargo build --verbose --all
      - cargo test --verbose --all
