[package]
name = "storious"
version = "0.0.1"
edition = "2018"
authors = ["kayak <kayak@kayak.rocks>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
